### ISSUE TITLE
Punishment Timers Broken

### ISSUE THREAD

**Issue by tweirtx** [FRCDiscord/Dozer#182]
Idk why but punishment timers aren't working at all

**Comment by bkeeneykid** [comment]
Traceback from the server:
```
0|Dozer    | Task exception was never retrieved
0|Dozer    | future: <Task finished name='Task-679183' coro=<Moderation.punishment_timer() done, defined at /home/travis/Dozer/dozer/cogs/moderation.py:97> exception=UndefinedColumnError('column "type_of_punishment" of relation "punishment_timers" does not exist')>
0|Dozer    | Traceback (most recent call last):
0|Dozer    |   File "/home/travis/Dozer/dozer/cogs/moderation.py", line 113, in punishment_timer
0|Dozer    |     await ent.update_or_add()
0|Dozer    |   File "/home/travis/Dozer/dozer/db.py", line 84, in update_or_add
0|Dozer    |     await conn.execute(statement, *values)
0|Dozer    |   File "/home/travis/.pyenv/versions/3.8.2/lib/python3.8/site-packages/asyncpg/connection.py", line 274, in execute
0|Dozer    |     _, status, _ = await self._execute(query, args, 0, timeout, True)
0|Dozer    |   File "/home/travis/.pyenv/versions/3.8.2/lib/python3.8/site-packages/asyncpg/connection.py", line 1402, in _execute
0|Dozer    |     result, _ = await self.__execute(
0|Dozer    |   File "/home/travis/.pyenv/versions/3.8.2/lib/python3.8/site-packages/asyncpg/connection.py", line 1411, in __execute
0|Dozer    |     return await self._do_execute(query, executor, timeout)
0|Dozer    |   File "/home/travis/.pyenv/versions/3.8.2/lib/python3.8/site-packages/asyncpg/connection.py", line 1426, in _do_execute
0|Dozer    |     stmt = await self._get_statement(query, timeout)
0|Dozer    |   File "/home/travis/.pyenv/versions/3.8.2/lib/python3.8/site-packages/asyncpg/connection.py", line 328, in _get_statement
0|Dozer    |     statement = await self._protocol.prepare(stmt_name, query, timeout)
0|Dozer    |   File "asyncpg/protocol/protocol.pyx", line 163, in prepare
0|Dozer    | asyncpg.exceptions.UndefinedColumnError: column "type_of_punishment" of relation "punishment_timers" does not exist
```
